let homeItemsData = [
    {
      id: "11",
      name: "Chicken Biryani",
      price: 15,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "https://swatisani.net/kitchen/wp-content/uploads/2015/10/IMG_9526.jpg",
    },
    {
        id: "12",
        name: "Chicken Fry Biryani",
        price: 200,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "https://b.zmtcdn.com/data/dish_photos/23f/9e849f47387ecf5eb69d29c7a900323f.jpg?output-format=webp",
    },
    {
      id: "13",
      name: "Prawns Biryani",
      price: 20,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "https://b.zmtcdn.com/data/dish_photos/699/d916fad951080e4ed88f2139a4428699.jpg?output-format=webp",
    },
    {
      id: "14",
      name: "Mutton Biryani",
      price: 25,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "https://b.zmtcdn.com/data/dish_photos/47c/eefbbee591baed8340930c2307e8a47c.jpg?output-format=webp",
    },
    {
      id: "15",
      name: "Kaju Biryani",
      price: 17,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "https://b.zmtcdn.com/data/dish_photos/cf5/34c77d7e8c68b60e0f96eaaf8ffb1cf5.jpg?output-format=webp",
    },
    {
      id: "16",
      name: "Paneer Biryani",
      price: 15,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "https://b.zmtcdn.com/data/dish_photos/896/cb446fd1d05955576058f674587dc896.jpg?output-format=webp",
    },
    {
      id: "21",
      name: "Chicken Manchuria",
      price: 10,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "https://indianpakwan.com/wp-content/uploads/2021/01/Chicken-manchurian-1200x676.jpg",
    },
    {
      id: "22",
      name: "Chicken Crispy Wings",
      price: 12,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "https://b.zmtcdn.com/data/dish_photos/bf5/ed344689d7e844371094fe776619cbf5.jpg",
    },
    {
      id: "23",
      name: "Noodles",
      price: 8,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "https://b.zmtcdn.com/data/dish_photos/09d/bcf455b8a58e1ddd0d2bed349833d09d.jpg",
    },
    {
      id: "24",
      name: "Loose Prawns",
      price: 14,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "https://b.zmtcdn.com/data/dish_photos/3a7/32709c437465fbb3b13c113f15c8b3a7.jpg?output-format=webp",
    },
    {
      id: "25",
      name: "Chicken Tandoori",
      price: 20,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "https://b.zmtcdn.com/data/dish_photos/3fa/d83e6b2b4eacdac0cd50e84d648073fa.jpg",
    },
    {
      id: "26",
      name: "Crispy Corn",
      price: 350,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "https://b.zmtcdn.com/data/dish_photos/128/4c8a1a414c62aa62861d2ea72cb60128.jpg?output-format=webp",
    },
    {
        id: "31",
        name: "Peppy Paneer",
        price: 8,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "https://b.zmtcdn.com/data/pictures/4/2800004/bedddb08e3eafa541fdec9db26613993.jpg?fit=around|771.75:416.25&crop=771.75:416.25;*,*",
      },
      {
        id: "32",
        name: "Golden Corn Pizza",
        price: 9,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "https://images.dominos.co.in/pizza_mania_golden_corn.png",
      },
      {
        id: "33",
        name: "Chicken Golden Delight",
        price: 8,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "https://images.dominos.co.in/new_chicken_golden_delight.jpg",
      },
      {
        id: "34",
        name: "Non Veg Supreme",
        price: 15,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "https://images.dominos.co.in/new_non_veg_supreme.jpg",
      },
      {
        id: "35",
        name: "Keema Do Pyaza",
        price: 20,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "https://images.dominos.co.in/updated_keema_do_pyaza.jpg",
      },
      {
        id: "36",
        name: "Indi Chicken Tikka",
        price: 23,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "https://images.dominos.co.in/IndianTandooriChickenTikka.jpg",
      },
  ]